export const siteConfig = {
    title: 'klanservicehub',
    description: 'Enterprise project management, issue tracking, and team collaboration suite.',
    keywords: [
        'reactjs',
        'nextjs',
        'appwrite',
        'appwrite-io',
        'next-auth',
        'react-big-calendar',
        'lucide-icons',
        'react-icons',
        'react-day-picker',
        'shadcn-ui',
        'radix-ui',
        'tailwindcss',
        'lodash',
        'react-query',
        'nuqs',
        'sonner',
        'typescript',
        'javascript',
        'vercel',
        'postcss',
        'prettier',
        'eslint',
        'react-dom',
        'html',
        'css',
        'nuqs-state-management',
        'infinite-query',
        'real-time-features',
        'organized-table',
        'filter-table',
        'paginate-table',
        'tasks-management',
        'projects-management',
        'workspaces-management',
        'ui/ux',
        'appwrite-db',
        'ticketing-tool',
        'date-fns',
        'cn',
        'clsx',
        'lucide-react',
    ],
    authors: {
        name: 'Klanvision IT Solutions Private Limited',
        url: 'https://klanvision.com',
    },
};
export const links = {
    corporate: 'https://klanvision.com',
    support: 'mailto:support@klanvision.com',
};